ghcr_owner: fpuhlig

redis_host: "{{ lookup('env', 'REDIS_HOST') | default('10.0.0.1', true) }}"
redis_port: 6379

backend_image: "ghcr.io/{{ ghcr_owner }}/restekoch-backend:latest"
frontend_image: "ghcr.io/{{ ghcr_owner }}/restekoch-frontend:latest"
